# Generated by Django 6.0.4 on 2026-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
